name: Server CI/CD Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive # Sentry

    - name: Configure CMake
      # -S Server: CMakeLists.txt 파일이 Server 폴더 안에 있음을 명시
      run: cmake -B build -S Server -DCMAKE_BUILD_TYPE=Release -A x64

    - name: Build Server
      # 생성된 build 폴더를 기준으로 빌드
      run: cmake --build build --config Release

    - name: Upload Build Artifacts
      # 빌드 결과물(.exe, .dll) 저장
      uses: actions/upload-artifact@v4
      with:
        name: Final-Server-Build
        path: |
          build/Release/*.exe
          build/Release/*.dll
          build/Release/*.pdb
          build/Release/crashpad_handler.exe