name: Server CI/CD Build

on:
  push:
    branches: [ "main", "develop", "feature/Server" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive # Sentry 소스 코드를 가져오기 위해 필수

    - name: Configure CMake
      # 최상위 CMakeLists.txt를 읽어 build 폴더에 설정 생성
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -A x64

    - name: Build Server
      run: cmake --build build --config Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Final-Server-Build
        path: |
          build/Release/*.exe
          build/Release/*.dll
          build/Release/*.pdb
          build/Release/crashpad_handler.exe